{
 "title": "Node metrics",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "[JSON-RPC] Request Ccount",
   "type": "timeseries",
   "description": "This graph shows the JSON-RPC API connection count.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  count - lag(count) OVER (ORDER BY \"time\") AS count\nFROM jsonrpc_request_duration\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "[JSON-RPC] Request Duration",
   "type": "timeseries",
   "description": "This graph shows the duration of the JSON-RPC API HTTP requests in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "[JSON-RPC] Batch requests per min",
   "type": "stat",
   "description": "This gauge shows the number of processed JSON-RPC request batches.",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jsonrpc_request_handled{instance=\"zkevm-rpc:9091\", type=\"batch\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[JSON-RPC] Single requests per min",
   "type": "stat",
   "description": "This gauge shows the number of processed JSON-RPC single requests.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(jsonrpc_request_handled{instance=\"zkevm-rpc:9091\", type=\"single\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[AGGREGATOR] Connected Provers",
   "type": "timeseries",
   "description": "This graph shows the number of currently connected prover instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "aggregator_current_connected_provers{instance=\"zkevm-aggregator:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[AGGREGATOR] Number of provers with jobs",
   "type": "timeseries",
   "description": "This graph shows the number of prover instances that have actively running jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "aggregator_current_working_provers{instance=\"zkevm-aggregator:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[SEQUENCER] Sequences sent to L1",
   "type": "timeseries",
   "description": "This graph show the number of sequences that were sent to the L1.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sequencer_sequences_sent_to_L1_count{instance=\"zkevm-sequencer:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[SEQUENCER] Reward for a sequence in MATIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sequencer_sequence_reward_in_matic{instance=\"zkevm-sequencer:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[SEQUENCER] Estimated average gas price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sequencer_gas_price_estimated_average{instance=\"zkevm-sequencer:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[SEQUENCER] ETH to MATIC price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "sequencer_eth_to_matic_price{instance=\"zkevm-sequencer:9091\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}